name: canue
channels:
  - conda-forge
dependencies:
  - python=3.10
  - openjdk=17.0.3
  - jupyterlab
  - geopy
  - altair
  - configargparse
  - fiona
  - geopandas
  - importlib_resources
  - joblib
  - jpype1
  - numpy
  - pandas
  - psutil
  - requests
  - pip
  - pip:
    - git+https://github.com/r5py/r5py.git@29da8da4fb1f07333772f9ac23236dfc8e0c4fbd