name: canue

channels:
    - conda-forge

dependencies:
    - python=3.10
    - folium
    - fiona
    - geopandas
    - importlib_resources
    - matplotlib
    - mapclassify
    - numpy
    - pandas
    - r5py
    - shapely
    - altair